TOOLCHAIN_PREFIX = arm-none-eabi-

CC = $(TOOLCHAIN_PREFIX)gcc
CXX = $(TOOLCHAIN_PREFIX)gcc
LINK = $(TOOLCHAIN_PREFIX)gcc
OBJCOPY = $(TOOLCHAIN_PREFIX)objcopy
AR = $(TOOLCHAIN_PREFIX)ar

NEWLIB_VERSION = 2.5.0
LIBCXX_VERSION = 5.0
LIBCXXRT_VERSION = 2017.08

COMMON_FLAGS = -mcpu=arm1176jzf-s -fpic -ffreestanding $(DEFINES) -DLIBCXXRT_WEAK_LOCKS -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_MONOTONIC_CLOCK -D_GNU_SOURCE -D_POSIX_TIMERS
COMMON_ASFLAGS = $(COMMON_FLAGS)
COMMON_CFLAGS = -std=gnu99 -O2 -Wall -Wextra $(COMMON_FLAGS)
COMMON_CXXFLAGS = -std=gnu++14 -O2 -Wall -Wextra -pedantic -fno-use-cxa-atexit -fno-threadsafe-statics $(COMMON_FLAGS)

MKDIR = mkdir
FIND = find
RM = rm
MAKE = make
COPY = cp

KERNEL_BIN = rpi-js-os
