MKDIR = mkdir
MAKE = make
NEWLIB_VERSION = 2.5.0

print-%  : ; @echo $* = $($*)

all: build/newlib
	cd build/newlib; \
	../../ext/newlib-$(NEWLIB_VERSION)/configure --target=arm-none-eabi; \
	$(MAKE)

build/newlib:
	$(MKDIR) -p build/newlib

.PHONY: all
